export const CATEGORY_ORDER = ['All', 'CRM', 'Communication', 'Marketing', 'Sales', 'Productivity', 'Finance', 'Ecommerce', 'Developer Tools', 'Support', 'HR'];

export const APPS = [
    { name: 'HubSpot', slug: 'hubspot', category: 'CRM' },
    { name: 'Zoho', slug: 'zoho', category: 'CRM' },
    { name: 'Discord', slug: 'discord', category: 'Communication' },
    { name: 'Gmail', slug: 'gmail', category: 'Communication' },
    { name: 'Slack', slug: 'slack', category: 'Communication' },
    { name: 'Telegram', slug: 'telegram', category: 'Communication' },
    { name: 'Twilio', slug: 'twilio', category: 'Communication' },
    { name: 'WhatsApp', slug: 'whatsapp', category: 'Communication' },
    { name: 'Zoom', slug: 'zoom', category: 'Communication' },
    { name: 'MailChimp', slug: 'mailchimp', category: 'Marketing' },
    { name: 'Typeform', slug: 'typeform', category: 'Marketing' },
    { name: 'Webflow', slug: 'webflow', category: 'Marketing' },
    { name: 'Calendly', slug: 'calendly', category: 'Sales' },
    { name: 'Salesforce', slug: 'salesforce', category: 'Sales' },
    { name: 'Airtable', slug: 'airtable', category: 'Productivity' },
    { name: 'Asana', slug: 'asana', category: 'Productivity' },
    { name: 'Box', slug: 'box', category: 'Productivity' },
    { name: 'ClickUp', slug: 'clickup', category: 'Productivity' },
    { name: 'Dropbox', slug: 'dropbox', category: 'Productivity' },
    { name: 'Google Calendar', slug: 'google-calendar', category: 'Productivity' },
    { name: 'Google Drive', slug: 'google-drive', category: 'Productivity' },
    { name: 'Google Sheets', slug: 'google-sheets', category: 'Productivity' },
    { name: 'Notion', slug: 'notion', category: 'Productivity' },
    { name: 'Trello', slug: 'trello', category: 'Productivity' },
    { name: 'PayPal', slug: 'paypal', category: 'Finance' },
    { name: 'QuickBooks', slug: 'quickbooks', category: 'Finance' },
    { name: 'Square', slug: 'square', category: 'Finance' },
    { name: 'Stripe', slug: 'stripe', category: 'Finance' },
    { name: 'Xero', slug: 'xero', category: 'Finance' },
    { name: 'Shopify', slug: 'shopify', category: 'Ecommerce' },
    { name: 'WooCommerce', slug: 'woocommerce', category: 'Ecommerce' },
    { name: 'Figma', slug: 'figma', category: 'Developer Tools' },
    { name: 'GitHub', slug: 'github', category: 'Developer Tools' },
    { name: 'Jira', slug: 'jira', category: 'Developer Tools' },
    { name: 'Linear', slug: 'linear', category: 'Developer Tools' },
    { name: 'Intercom', slug: 'intercom', category: 'Support' },
    { name: 'Zendesk', slug: 'zendesk', category: 'Support' },
    { name: 'Greenhouse', slug: 'greenhouse', category: 'HR' },
];
